events {}

http {
    log_format combined_log '$remote_addr - - [$time_local] '
                            '"$request" $status $body_bytes_sent '
                            '"$http_referer" "$http_user_agent"';

    access_log /var/log/nginx/access.log combined_log;

    server {
        listen 80;

        location /dvwa/ {
            proxy_pass http://dvwa:80/;
        }

        location /juice/ {
            proxy_pass http://juice_shop:3000/;
        }

        location /webgoat/ {
            proxy_pass http://webgoat:8080/;
        }
    }
}
